#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Oct 07, 2024 08:04:52 AM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import login_page_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1280x649+-8+-8")
        top.minsize(120, 1)
        top.maxsize(1284, 701)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.Canvas1 = tk.Canvas(self.top)
        self.Canvas1.place(relx=0.609, rely=0.0, relheight=1.068, relwidth=0.391)

        self.Canvas1.configure(background="#dbe6ff")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="#000000")
        self.Canvas1.configure(insertbackground="#000000")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#d9d9d9")
        self.Canvas1.configure(selectforeground="black")

        self.Enterpsword = tk.Entry(self.Canvas1)
        self.Enterpsword.place(relx=0.1, rely=0.548, height=30, relwidth=0.507)
        self.Enterpsword.configure(background="#f2f6fe")
        self.Enterpsword.configure(disabledforeground="#a3a3a3")
        self.Enterpsword.configure(font="TkFixedFont")
        self.Enterpsword.configure(foreground="black")
        self.Enterpsword.configure(highlightbackground="#d9d9d9")
        self.Enterpsword.configure(highlightcolor="#000000")
        self.Enterpsword.configure(insertbackground="#000000")
        self.Enterpsword.configure(selectbackground="#d9d9d9")
        self.Enterpsword.configure(selectforeground="black")

        self.SUBMIT = tk.Button(self.Canvas1)
        self.SUBMIT.place(relx=0.319, rely=0.736, height=26, width=117)
        self.SUBMIT.configure(activebackground="#d9d9d9")
        self.SUBMIT.configure(activeforeground="black")
        self.SUBMIT.configure(background="#f2f6fe")
        self.SUBMIT.configure(disabledforeground="#a3a3a3")
        self.SUBMIT.configure(font="-family {Segoe UI Emoji} -size 12 -weight bold")
        self.SUBMIT.configure(foreground="black")
        self.SUBMIT.configure(highlightbackground="#d9d9d9")
        self.SUBMIT.configure(highlightcolor="#000000")
        self.SUBMIT.configure(text='''SUBMIT''')

        self.LOGIN = tk.Label(self.Canvas1)
        self.LOGIN.place(relx=0.279, rely=0.072, height=50, width=204)
        self.LOGIN.configure(activebackground="#d9d9d9")
        self.LOGIN.configure(activeforeground="black")
        self.LOGIN.configure(anchor='w')
        self.LOGIN.configure(background="#dbe6ff")
        self.LOGIN.configure(compound='left')
        self.LOGIN.configure(disabledforeground="#a3a3a3")
        self.LOGIN.configure(font="-family {Browallia New} -size 48 -weight bold -underline 1")
        self.LOGIN.configure(foreground="black")
        self.LOGIN.configure(highlightbackground="#d9d9d9")
        self.LOGIN.configure(highlightcolor="#000000")
        self.LOGIN.configure(text='''LOGIN''')

        self.USERID = tk.Label(self.Canvas1)
        self.USERID.place(relx=0.1, rely=0.332, height=31, width=114)
        self.USERID.configure(activebackground="#d9d9d9")
        self.USERID.configure(activeforeground="black")
        self.USERID.configure(anchor='w')
        self.USERID.configure(background="#dbe6ff")
        self.USERID.configure(compound='left')
        self.USERID.configure(disabledforeground="#a3a3a3")
        self.USERID.configure(font="-family {Segoe UI Black} -size 14 -weight bold")
        self.USERID.configure(foreground="black")
        self.USERID.configure(highlightbackground="#d9d9d9")
        self.USERID.configure(highlightcolor="#000000")
        self.USERID.configure(text='''USER ID''')

        self.PASSWORD = tk.Label(self.Canvas1)
        self.PASSWORD.place(relx=0.1, rely=0.505, height=21, width=174)
        self.PASSWORD.configure(activebackground="#d9d9d9")
        self.PASSWORD.configure(activeforeground="black")
        self.PASSWORD.configure(anchor='w')
        self.PASSWORD.configure(background="#dbe6ff")
        self.PASSWORD.configure(compound='left')
        self.PASSWORD.configure(disabledforeground="#a3a3a3")
        self.PASSWORD.configure(font="-family {Segoe UI Black} -size 14 -weight bold")
        self.PASSWORD.configure(foreground="black")
        self.PASSWORD.configure(highlightbackground="#d9d9d9")
        self.PASSWORD.configure(highlightcolor="#000000")
        self.PASSWORD.configure(text='''PASSWORD''')

        self.EnterID = tk.Entry(self.Canvas1)
        self.EnterID.place(relx=0.1, rely=0.39, height=30, relwidth=0.487)
        self.EnterID.configure(background="#f2f6fe")
        self.EnterID.configure(disabledforeground="#a3a3a3")
        self.EnterID.configure(font="TkFixedFont")
        self.EnterID.configure(foreground="black")
        self.EnterID.configure(highlightbackground="#d9d9d9")
        self.EnterID.configure(highlightcolor="#000000")
        self.EnterID.configure(insertbackground="#000000")
        self.EnterID.configure(selectbackground="#d9d9d9")
        self.EnterID.configure(selectforeground="black")

        self.IMAGE = tk.Label(self.top)
        self.IMAGE.place(relx=-0.008, rely=0.0, height=661, width=805)
        self.IMAGE.configure(activebackground="#d9d9d9")
        self.IMAGE.configure(activeforeground="black")
        self.IMAGE.configure(anchor='w')
        self.IMAGE.configure(background="#d9d9d9")
        self.IMAGE.configure(compound='left')
        self.IMAGE.configure(disabledforeground="#a3a3a3")
        self.IMAGE.configure(foreground="#000000")
        self.IMAGE.configure(highlightbackground="#d9d9d9")
        self.IMAGE.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"../Image/login (1).png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.IMAGE.configure(image=_img0)
        self.IMAGE.configure(text='''USER ID:''')

def start_up():
    login_page_support.main()

if __name__ == '__main__':
    login_page_support.main()




