#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Oct 10, 2024 10:16:11 AM IST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import message_adm_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: message_adm_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class Message:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1326x675+-8+-8")
        top.minsize(18, 1)
        top.maxsize(1164, 240)
        top.resizable(1,  1)
        top.title("Message")
        top.configure(background="#dbe6ff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.Admin = tk.StringVar()

        self.Message1 = tk.Message(self.top)
        self.Message1.place(relx=0.053, rely=0.044, relheight=0.104
                , relwidth=0.192)
        self.Message1.configure(background="#dbe6ff")
        self.Message1.configure(font="-family {Arial Black} -size 24 -weight bold")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="#000000")
        self.Message1.configure(padx="1")
        self.Message1.configure(pady="1")
        self.Message1.configure(text='''Message''')
        self.Message1.configure(width=254)

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.784, rely=0.43, height=36, width=77)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#f2f6fe")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 9")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Send''')

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(relx=0.09, rely=0.148, height=160, relwidth=0.765)
        self.Entry1.configure(background="#f2f6fe")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(exportselection="0")
        self.Entry1.configure(font="-family {Courier New} -size 10")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="#000000")
        self.Entry1.configure(insertbackground="#000000")
        self.Entry1.configure(relief="solid")
        self.Entry1.configure(selectbackground="#d9d9d9")
        self.Entry1.configure(selectforeground="black")

        #_style_code()
        self.TCombobox1 = ttk.Combobox(self.top)
        self.TCombobox1.place(relx=0.083, rely=0.533, relheight=0.037
                , relwidth=0.109)
        self.TCombobox1.configure(font="-family {Segoe UI Black} -size 10 -weight bold")
        self.TCombobox1.configure(textvariable=self.Admin)
        self.TCombobox1.configure(foreground="#252525")
        self.TCombobox1.configure(background="#f2f6fe")
        self.TCombobox1.configure(cursor="arrow")

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.211, rely=0.533, height=26, width=57)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#f2f6fe")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Segoe UI} -size 9")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="#000000")
        self.Button2.configure(text='''Show''')

        self.Text1 = tk.Text(self.top)
        self.Text1.place(relx=0.083, rely=0.607, relheight=0.304, relwidth=0.756)

        self.Text1.configure(background="#f2f6fe")
        self.Text1.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="#000000")
        self.Text1.configure(insertbackground="#000000")
        self.Text1.configure(selectbackground="#d9d9d9")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(setgrid="1")
        self.Text1.configure(spacing1="2")
        self.Text1.configure(spacing2="4")
        self.Text1.configure(spacing3="5")
        self.Text1.configure(tabs="3")

        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.875, rely=0.904, height=30, width=57)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(background="#f2f6fe")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font="-family {Segoe UI} -size 9")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="#000000")
        self.Button3.configure(text='''Back''')

def start_up():
    message_adm_support.main()

if __name__ == '__main__':
    message_adm_support.main()




