#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Oct 06, 2024 10:31:21 AM IST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import page2_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: page2_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x450+339+121")
        top.minsize(120, 1)
        top.maxsize(1330, 707)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.417, rely=0.6, height=26, width=47)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Back''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        _style_code()
        self.TFrame1 = ttk.Frame(self.top)
        self.TFrame1.place(relx=0.05, rely=0.044, relheight=0.167
                , relwidth=0.892)
        self.TFrame1.configure(relief='solid')
        self.TFrame1.configure(borderwidth="2")
        self.TFrame1.configure(relief="solid")

        self.Message1 = tk.Message(self.TFrame1)
        self.Message1.place(relx=0.43, rely=0.4, relheight=0.253, relwidth=0.093)

        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="#000000")
        self.Message1.configure(padx="1")
        self.Message1.configure(pady="1")
        self.Message1.configure(text='''Test Page''')
        self.Message1.configure(width=60)

        self.Canvas1 = tk.Canvas(self.top)
        self.Canvas1.place(relx=0.25, rely=0.267, relheight=0.184
                , relwidth=0.538)
        self.Canvas1.configure(background="#7952ef")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="#694bf5")
        self.Canvas1.configure(insertbackground="#694bf5")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#d9d9d9")
        self.Canvas1.configure(selectforeground="#7952ef")

        self.Label1_1 = tk.Label(self.top)
        self.Label1_1.place(relx=0.583, rely=0.311, height=31, width=84)
        self.Label1_1.configure(activebackground="#d9d9d9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(anchor='w')
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(compound='left')
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Segoe UI} -size 9")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"./images/close_active.gif")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1_1.configure(image=_img0)
        self.Label1_1.configure(relief="groove")
        self.Label1_1.configure(text='''Test Var''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.283, rely=0.311, height=31, width=84)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"./images/close_active.gif")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img1)
        self.Label1.configure(relief="groove")
        self.Label1.configure(text='''Test Var''')

def start_up():
    page2_support.main()

if __name__ == '__main__':
    page2_support.main()




