#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Oct 09, 2024 03:37:01 PM IST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import atd_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

from PIL import Image, ImageTk

class stu_atd:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1280x657+-8+-8")
        top.minsize(120, 1)
        top.maxsize(1284, 701)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#dbe6ff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.atd = tk.Message(self.top)
        self.atd.place(relx=0.078, rely=0.167, relheight=0.085, relwidth=0.334)
        self.atd.configure(background="#dbe6ff")
        self.atd.configure(font="-family {Sitka Display} -size 48 -weight bold")
        self.atd.configure(foreground="#000000")
        self.atd.configure(highlightbackground="#d9d9d9")
        self.atd.configure(highlightcolor="#000000")
        self.atd.configure(padx="1")
        self.atd.configure(pady="1")
        self.atd.configure(text='''ATTENDENCE''')
        self.atd.configure(width=427)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.total = tk.Message(self.top)
        self.total.place(relx=0.117, rely=0.426, relheight=0.044, relwidth=0.076)

        self.total.configure(background="#dbe6ff")
        self.total.configure(font="-family {@Yu Gothic UI Semibold} -size 20 -weight bold")
        self.total.configure(foreground="#000000")
        self.total.configure(highlightbackground="#d9d9d9")
        self.total.configure(highlightcolor="#000000")
        self.total.configure(padx="1")
        self.total.configure(pady="1")
        self.total.configure(text='''Total -''')
        self.total.configure(width=97)

        self.pst = tk.Message(self.top)
        self.pst.place(relx=0.102, rely=0.502, relheight=0.059, relwidth=0.091)
        self.pst.configure(background="#dbe6ff")
        self.pst.configure(font="-family {@Yu Gothic UI Semibold} -size 20 -weight bold")
        self.pst.configure(foreground="#000000")
        self.pst.configure(highlightbackground="#d9d9d9")
        self.pst.configure(highlightcolor="#000000")
        self.pst.configure(padx="1")
        self.pst.configure(pady="1")
        self.pst.configure(text='''Present -''')
        self.pst.configure(width=116)

        self.total_opt = tk.Text(self.top)
        self.total_opt.place(relx=0.211, rely=0.426, relheight=0.052
                , relwidth=0.066)
        self.total_opt.configure(background="#f2f6fe")
        self.total_opt.configure(font="TkTextFont")
        self.total_opt.configure(foreground="black")
        self.total_opt.configure(highlightbackground="#d9d9d9")
        self.total_opt.configure(highlightcolor="#000000")
        self.total_opt.configure(insertbackground="#000000")
        self.total_opt.configure(selectbackground="#d9d9d9")
        self.total_opt.configure(selectforeground="black")
        self.total_opt.configure(wrap="word")

        self.pst_opt = tk.Text(self.top)
        self.pst_opt.place(relx=0.211, rely=0.502, relheight=0.052
                , relwidth=0.066)
        self.pst_opt.configure(background="#f2f6fe")
        self.pst_opt.configure(font="TkTextFont")
        self.pst_opt.configure(foreground="black")
        self.pst_opt.configure(highlightbackground="#d9d9d9")
        self.pst_opt.configure(highlightcolor="#000000")
        self.pst_opt.configure(insertbackground="#000000")
        self.pst_opt.configure(selectbackground="#d9d9d9")
        self.pst_opt.configure(selectforeground="black")
        self.pst_opt.configure(wrap="word")

        self.abst = tk.Message(self.top)
        self.abst.place(relx=0.102, rely=0.578, relheight=0.058, relwidth=0.098)
        self.abst.configure(background="#dbe6ff")
        self.abst.configure(font="-family {@Yu Gothic UI Semibold} -size 20 -weight bold")
        self.abst.configure(foreground="#000000")
        self.abst.configure(highlightbackground="#d9d9d9")
        self.abst.configure(highlightcolor="#000000")
        self.abst.configure(padx="1")
        self.abst.configure(pady="1")
        self.abst.configure(text='''Absent -''')
        self.abst.configure(width=126)

        self.per = tk.Message(self.top)
        self.per.place(relx=0.086, rely=0.7, relheight=0.088, relwidth=0.184)
        self.per.configure(background="#dbe6ff")
        self.per.configure(font="-family {@Yu Gothic UI Semibold} -size 36 -weight bold")
        self.per.configure(foreground="#000000")
        self.per.configure(highlightbackground="#d9d9d9")
        self.per.configure(highlightcolor="#000000")
        self.per.configure(padx="1")
        self.per.configure(pady="1")
        self.per.configure(text='''Percent -''')
        self.per.configure(width=235)

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.82, rely=0.868, height=36, width=97)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI Semibold} -size 11 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''BACK''')

        self.abst_opt = tk.Text(self.top)
        self.abst_opt.place(relx=0.211, rely=0.578, relheight=0.052
                , relwidth=0.066)
        self.abst_opt.configure(background="#f2f6fe")
        self.abst_opt.configure(font="TkTextFont")
        self.abst_opt.configure(foreground="black")
        self.abst_opt.configure(highlightbackground="#d9d9d9")
        self.abst_opt.configure(highlightcolor="#000000")
        self.abst_opt.configure(insertbackground="#000000")
        self.abst_opt.configure(selectbackground="#d9d9d9")
        self.abst_opt.configure(selectforeground="black")
        self.abst_opt.configure(wrap="word")

        self.per_opt = tk.Text(self.top)
        self.per_opt.place(relx=0.281, rely=0.715, relheight=0.067
                , relwidth=0.12)
        self.per_opt.configure(background="#f2f6fe")
        self.per_opt.configure(font="TkTextFont")
        self.per_opt.configure(foreground="black")
        self.per_opt.configure(highlightbackground="#d9d9d9")
        self.per_opt.configure(highlightcolor="#000000")
        self.per_opt.configure(insertbackground="#000000")
        self.per_opt.configure(selectbackground="#d9d9d9")
        self.per_opt.configure(selectforeground="black")
        self.per_opt.configure(wrap="word")

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.555, rely=0.183, height=341, width=338)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="black")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"Untitled1.png")
        global _img0
        _img0 = ImageTk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)

def start_up():
    atd_support.main()

if __name__ == '__main__':
    atd_support.main()




