#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Oct 10, 2024 04:40:08 PM IST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import student_profile_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This cls configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1280x657+-8+-8")
        top.minsize(120, 1)
        top.maxsize(1284, 701)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#dbe6ff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Text1_1_1 = tk.Text(self.top)
        self.Text1_1_1.place(relx=0.242, rely=0.807, relheight=0.053
                , relwidth=0.175)
        self.Text1_1_1.configure(background="white")
        self.Text1_1_1.configure(font="TkTextFont")
        self.Text1_1_1.configure(foreground="black")
        self.Text1_1_1.configure(highlightbackground="#d9d9d9")
        self.Text1_1_1.configure(highlightcolor="#000000")
        self.Text1_1_1.configure(insertbackground="#000000")
        self.Text1_1_1.configure(selectbackground="#d9d9d9")
        self.Text1_1_1.configure(selectforeground="black")
        self.Text1_1_1.configure(wrap="word")

        self.Text1_1 = tk.Text(self.top)
        self.Text1_1.place(relx=0.242, rely=0.731, relheight=0.053
                , relwidth=0.175)
        self.Text1_1.configure(background="white")
        self.Text1_1.configure(font="TkTextFont")
        self.Text1_1.configure(foreground="black")
        self.Text1_1.configure(highlightbackground="#d9d9d9")
        self.Text1_1.configure(highlightcolor="#000000")
        self.Text1_1.configure(insertbackground="#000000")
        self.Text1_1.configure(selectbackground="#d9d9d9")
        self.Text1_1.configure(selectforeground="black")
        self.Text1_1.configure(wrap="word")

        self.Text1 = tk.Text(self.top)
        self.Text1.place(relx=0.242, rely=0.654, relheight=0.052, relwidth=0.175)

        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="#000000")
        self.Text1.configure(insertbackground="#000000")
        self.Text1.configure(selectbackground="#d9d9d9")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")

        self.Text1_2 = tk.Text(self.top)
        self.Text1_2.place(relx=0.242, rely=0.578, relheight=0.052
                , relwidth=0.175)
        self.Text1_2.configure(background="white")
        self.Text1_2.configure(font="TkTextFont")
        self.Text1_2.configure(foreground="black")
        self.Text1_2.configure(highlightbackground="#d9d9d9")
        self.Text1_2.configure(highlightcolor="#000000")
        self.Text1_2.configure(insertbackground="#000000")
        self.Text1_2.configure(selectbackground="#d9d9d9")
        self.Text1_2.configure(selectforeground="black")
        self.Text1_2.configure(wrap="word")

        self.Text1_2_1 = tk.Text(self.top)
        self.Text1_2_1.place(relx=0.242, rely=0.502, relheight=0.052
                , relwidth=0.175)
        self.Text1_2_1.configure(background="white")
        self.Text1_2_1.configure(font="TkTextFont")
        self.Text1_2_1.configure(foreground="black")
        self.Text1_2_1.configure(highlightbackground="#d9d9d9")
        self.Text1_2_1.configure(highlightcolor="#000000")
        self.Text1_2_1.configure(insertbackground="#000000")
        self.Text1_2_1.configure(selectbackground="#d9d9d9")
        self.Text1_2_1.configure(selectforeground="black")
        self.Text1_2_1.configure(wrap="word")

        self.Text1_2_1_1 = tk.Text(self.top)
        self.Text1_2_1_1.place(relx=0.242, rely=0.426, relheight=0.052
                , relwidth=0.175)
        self.Text1_2_1_1.configure(background="white")
        self.Text1_2_1_1.configure(font="TkTextFont")
        self.Text1_2_1_1.configure(foreground="black")
        self.Text1_2_1_1.configure(highlightbackground="#d9d9d9")
        self.Text1_2_1_1.configure(highlightcolor="#000000")
        self.Text1_2_1_1.configure(insertbackground="#000000")
        self.Text1_2_1_1.configure(selectbackground="#d9d9d9")
        self.Text1_2_1_1.configure(selectforeground="black")
        self.Text1_2_1_1.configure(wrap="word")

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.844, rely=0.898, height=26, width=77)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#dbe6ff")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''BACK''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.578, rely=0.183, height=352, width=381)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"C:\\Users\\RAJ KISHORE\\Desktop\\IP Project\\School-management-\\Test\\Image\\login (1).png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)

        self.heading = tk.Message(self.top)
        self.heading.place(relx=0.047, rely=0.061, relheight=0.11
                , relwidth=0.161)
        self.heading.configure(background="#dbe6ff")
        self.heading.configure(font="-family {Sitka Display} -size 48 -weight bold")
        self.heading.configure(foreground="#000000")
        self.heading.configure(highlightbackground="#d9d9d9")
        self.heading.configure(highlightcolor="#000000")
        self.heading.configure(padx="1")
        self.heading.configure(pady="1")
        self.heading.configure(text='''Profile''')
        self.heading.configure(width=206)

        self.Text1_2_1_1_1_1 = tk.Text(self.top)
        self.Text1_2_1_1_1_1.place(relx=0.242, rely=0.274, relheight=0.052
                , relwidth=0.175)
        self.Text1_2_1_1_1_1.configure(background="white")
        self.Text1_2_1_1_1_1.configure(font="TkTextFont")
        self.Text1_2_1_1_1_1.configure(foreground="black")
        self.Text1_2_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Text1_2_1_1_1_1.configure(highlightcolor="#000000")
        self.Text1_2_1_1_1_1.configure(insertbackground="#000000")
        self.Text1_2_1_1_1_1.configure(selectbackground="#d9d9d9")
        self.Text1_2_1_1_1_1.configure(selectforeground="black")
        self.Text1_2_1_1_1_1.configure(wrap="word")

        self.name = tk.Message(self.top)
        self.name.place(relx=0.086, rely=0.274, relheight=0.058, relwidth=0.063)
        self.name.configure(background="#dbe6ff")
        self.name.configure(font="-family {Arial} -size 17 -weight bold")
        self.name.configure(foreground="#000000")
        self.name.configure(highlightbackground="#d9d9d9")
        self.name.configure(highlightcolor="#000000")
        self.name.configure(padx="1")
        self.name.configure(pady="1")
        self.name.configure(text='''Name :''')
        self.name.configure(width=81)

        self.Text1_2_1_1_1 = tk.Text(self.top)
        self.Text1_2_1_1_1.place(relx=0.242, rely=0.35, relheight=0.052
                , relwidth=0.175)
        self.Text1_2_1_1_1.configure(background="white")
        self.Text1_2_1_1_1.configure(font="TkTextFont")
        self.Text1_2_1_1_1.configure(foreground="black")
        self.Text1_2_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Text1_2_1_1_1.configure(highlightcolor="#000000")
        self.Text1_2_1_1_1.configure(insertbackground="#000000")
        self.Text1_2_1_1_1.configure(selectbackground="#d9d9d9")
        self.Text1_2_1_1_1.configure(selectforeground="black")
        self.Text1_2_1_1_1.configure(wrap="word")

        self.cls = tk.Message(self.top)
        self.cls.place(relx=0.078, rely=0.35, relheight=0.044, relwidth=0.08)
        self.cls.configure(background="#dbe6ff")
        self.cls.configure(font="-family {Arial} -size 17 -weight bold")
        self.cls.configure(foreground="#000000")
        self.cls.configure(highlightbackground="#d9d9d9")
        self.cls.configure(highlightcolor="#000000")
        self.cls.configure(padx="1")
        self.cls.configure(pady="1")
        self.cls.configure(text='''Class :''')
        self.cls.configure(width=101)

        self.sec = tk.Message(self.top)
        self.sec.place(relx=0.07, rely=0.411, relheight=0.075, relwidth=0.08)
        self.sec.configure(background="#dbe6ff")
        self.sec.configure(cursor="fleur")
        self.sec.configure(font="-family {Arial} -size 17 -weight bold")
        self.sec.configure(foreground="#000000")
        self.sec.configure(highlightbackground="#d9d9d9")
        self.sec.configure(highlightcolor="#000000")
        self.sec.configure(padx="1")
        self.sec.configure(pady="1")
        self.sec.configure(text='''Sec :''')
        self.sec.configure(width=102)

        self.roll = tk.Message(self.top)
        self.roll.place(relx=0.07, rely=0.502, relheight=0.044, relwidth=0.109)
        self.roll.configure(background="#dbe6ff")
        self.roll.configure(font="-family {Arial} -size 17 -weight bold")
        self.roll.configure(foreground="#000000")
        self.roll.configure(highlightbackground="#d9d9d9")
        self.roll.configure(highlightcolor="#000000")
        self.roll.configure(padx="1")
        self.roll.configure(pady="1")
        self.roll.configure(text='''Roll no :''')
        self.roll.configure(width=140)

        self.adm = tk.Message(self.top)
        self.adm.place(relx=0.07, rely=0.578, relheight=0.059, relwidth=0.109)
        self.adm.configure(background="#dbe6ff")
        self.adm.configure(font="-family {Arial} -size 17 -weight bold")
        self.adm.configure(foreground="#000000")
        self.adm.configure(highlightbackground="#d9d9d9")
        self.adm.configure(highlightcolor="#000000")
        self.adm.configure(padx="1")
        self.adm.configure(pady="1")
        self.adm.configure(text='''Adm no :''')
        self.adm.configure(width=140)

        self.fname = tk.Message(self.top)
        self.fname.place(relx=0.07, rely=0.654, relheight=0.058, relwidth=0.163)
        self.fname.configure(background="#dbe6ff")
        self.fname.configure(font="-family {Arial} -size 17 -weight bold")
        self.fname.configure(foreground="#000000")
        self.fname.configure(highlightbackground="#d9d9d9")
        self.fname.configure(highlightcolor="#000000")
        self.fname.configure(padx="1")
        self.fname.configure(pady="1")
        self.fname.configure(text='''Father's Name :''')
        self.fname.configure(width=208)

        self.mname = tk.Message(self.top)
        self.mname.place(relx=0.07, rely=0.731, relheight=0.058
                , relwidth=0.163)
        self.mname.configure(background="#dbe6ff")
        self.mname.configure(font="-family {Arial} -size 17 -weight bold")
        self.mname.configure(foreground="#000000")
        self.mname.configure(highlightbackground="#d9d9d9")
        self.mname.configure(highlightcolor="#000000")
        self.mname.configure(padx="1")
        self.mname.configure(pady="1")
        self.mname.configure(text='''Mother's Name :''')
        self.mname.configure(width=208)

        self.Message2_1_1_1_1_2 = tk.Message(self.top)
        self.Message2_1_1_1_1_2.place(relx=0.075, rely=0.807, relheight=0.043
                , relwidth=0.095)
        self.Message2_1_1_1_1_2.configure(background="#dbe6ff")
        self.Message2_1_1_1_1_2.configure(font="-family {Arial} -size 17 -weight bold")
        self.Message2_1_1_1_1_2.configure(foreground="#000000")
        self.Message2_1_1_1_1_2.configure(highlightbackground="#d9d9d9")
        self.Message2_1_1_1_1_2.configure(highlightcolor="#000000")
        self.Message2_1_1_1_1_2.configure(padx="1")
        self.Message2_1_1_1_1_2.configure(pady="1")
        self.Message2_1_1_1_1_2.configure(text='''Address :''')
        self.Message2_1_1_1_1_2.configure(width=121)

def start_up():
    student_profile_support.main()

if __name__ == '__main__':
    student_profile_support.main()




