#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Oct 08, 2024 04:57:17 PM IST  platform: Windows NT
#asdfgh
import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import time_table_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: time_table_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class Time_table:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1326x675+-5+0")
        top.minsize(120, 1)
        top.maxsize(1330, 727)
        top.resizable(1,  1)
        top.title("Time_table")
        top.configure(background="#dbe6ff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.136, rely=0.178, relheight=0.72, relwidth=0.683)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#f2f6fe")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#000000")

        _style_code()
        self.TSeparator1 = ttk.Separator(self.Frame1)
        self.TSeparator1.place(relx=0.003, rely=0.311,  relwidth=1.159)

        self.TSeparator3 = ttk.Separator(self.Frame1)
        self.TSeparator3.place(relx=-0.009, rely=0.827,  relwidth=1.163)

        self.TSeparator1_1 = ttk.Separator(self.Frame1)
        self.TSeparator1_1.place(relx=-0.006, rely=0.481,  relwidth=1.177)

        self.TSeparator2 = ttk.Separator(self.Frame1)
        self.TSeparator2.place(relx=-0.007, rely=0.642,  relwidth=1.163)

        self.TSeparator6 = ttk.Separator(self.Frame1)
        self.TSeparator6.place(relx=0.499, rely=0.004,  relheight=0.988)
        self.TSeparator6.configure(orient="vertical")

        self.TSeparator5 = ttk.Separator(self.Frame1)
        self.TSeparator5.place(relx=0.366, rely=0.004,  relheight=0.988)
        self.TSeparator5.configure(orient="vertical")

        self.TSeparator4 = ttk.Separator(self.Frame1)
        self.TSeparator4.place(relx=0.245, rely=0.004,  relheight=0.988)
        self.TSeparator4.configure(orient="vertical")

        self.TSeparator7 = ttk.Separator(self.Frame1)
        self.TSeparator7.place(relx=0.62, rely=0.004,  relheight=0.988)
        self.TSeparator7.configure(orient="vertical")

        self.TSeparator8 = ttk.Separator(self.Frame1)
        self.TSeparator8.place(relx=0.753, rely=0.004,  relheight=0.988)
        self.TSeparator8.configure(orient="vertical")

        self.TSeparator10 = ttk.Separator(self.Frame1)
        self.TSeparator10.place(relx=1.007, rely=0.004,  relheight=0.988)
        self.TSeparator10.configure(orient="vertical")

        self.TSeparator9 = ttk.Separator(self.Frame1)
        self.TSeparator9.place(relx=0.874, rely=0.004,  relheight=0.988)
        self.TSeparator9.configure(orient="vertical")

        self.Message3 = tk.Message(self.Frame1)
        self.Message3.place(relx=0.121, rely=0.165, relheight=0.121
                , relwidth=0.11)
        self.Message3.configure(background="#f2f6fe")
        self.Message3.configure(font="-family {Segoe UI} -size 16")
        self.Message3.configure(foreground="#000000")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="#000000")
        self.Message3.configure(padx="1")
        self.Message3.configure(pady="1")
        self.Message3.configure(text='''IP''')
        self.Message3.configure(width=100)

        self.Frame2 = tk.Frame(self.Frame1)
        self.Frame2.place(relx=0.0, rely=0.142, relheight=0.86, relwidth=0.106)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#f2f6fe")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="#000000")

        self.Message2 = tk.Message(self.Frame2)
        self.Message2.place(relx=0.104, rely=0.048, relheight=0.117
                , relwidth=0.833)
        self.Message2.configure(background="#f2f6fe")
        self.Message2.configure(font="-family {Segoe UI} -size 12")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="#000000")
        self.Message2.configure(padx="1")
        self.Message2.configure(pady="1")
        self.Message2.configure(text='''DAY-1''')
        self.Message2.configure(width=80)

        self.Message3_1_1_1_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1.place(relx=0.254, rely=0.165, relheight=0.121
                , relwidth=0.11)
        self.Message3_1_1_1_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1.configure(padx="1")
        self.Message3_1_1_1_1_1.configure(pady="1")
        self.Message3_1_1_1_1_1.configure(text='''Chemistry''')
        self.Message3_1_1_1_1_1.configure(width=100)

        self.Frame3 = tk.Frame(self.Frame1)
        self.Frame3.place(relx=0.104, rely=0.0, relheight=0.148, relwidth=0.896)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#f2f6fe")
        self.Frame3.configure(highlightbackground="#d9d9d9")
        self.Frame3.configure(highlightcolor="#000000")

        self.Message2_2_1_1_1_1_1 = tk.Message(self.Frame3)
        self.Message2_2_1_1_1_1_1.place(relx=0.025, rely=0.139, relheight=0.681
                , relwidth=0.099)
        self.Message2_2_1_1_1_1_1.configure(background="#f2f6fe")
        self.Message2_2_1_1_1_1_1.configure(font="-family {Segoe UI} -size 12")
        self.Message2_2_1_1_1_1_1.configure(foreground="#000000")
        self.Message2_2_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message2_2_1_1_1_1_1.configure(highlightcolor="#000000")
        self.Message2_2_1_1_1_1_1.configure(padx="1")
        self.Message2_2_1_1_1_1_1.configure(pady="1")
        self.Message2_2_1_1_1_1_1.configure(text='''Period-1''')
        self.Message2_2_1_1_1_1_1.configure(width=80)

        self.Message3_1_1_1_1_1_2_2 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_2.place(relx=0.508, rely=0.165, relheight=0.121
                , relwidth=0.11)
        self.Message3_1_1_1_1_1_2_2.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_2.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_2.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_2.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_2.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_2.configure(padx="1")
        self.Message3_1_1_1_1_1_2_2.configure(pady="1")
        self.Message3_1_1_1_1_1_2_2.configure(text='''Phe/
Painting''')
        self.Message3_1_1_1_1_1_2_2.configure(width=100)

        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1_1.place(relx=0.629, rely=0.165
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1_1.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1_1.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1_1.configure(text='''Maths''')
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1_1.configure(width=100)

        self.Message3_2 = tk.Message(self.Frame1)
        self.Message3_2.place(relx=0.762, rely=0.165, relheight=0.121
                , relwidth=0.11)
        self.Message3_2.configure(background="#f2f6fe")
        self.Message3_2.configure(font="-family {Segoe UI} -size 16")
        self.Message3_2.configure(foreground="#000000")
        self.Message3_2.configure(highlightbackground="#d9d9d9")
        self.Message3_2.configure(highlightcolor="#000000")
        self.Message3_2.configure(padx="1")
        self.Message3_2.configure(pady="1")
        self.Message3_2.configure(text='''English''')
        self.Message3_2.configure(width=100)

        self.Message3_2_2 = tk.Message(self.Frame1)
        self.Message3_2_2.place(relx=0.883, rely=0.165, relheight=0.121
                , relwidth=0.11)
        self.Message3_2_2.configure(background="#f2f6fe")
        self.Message3_2_2.configure(font="-family {Segoe UI} -size 16")
        self.Message3_2_2.configure(foreground="#000000")
        self.Message3_2_2.configure(highlightbackground="#d9d9d9")
        self.Message3_2_2.configure(highlightcolor="#000000")
        self.Message3_2_2.configure(padx="1")
        self.Message3_2_2.configure(pady="1")
        self.Message3_2_2.configure(text='''Library''')
        self.Message3_2_2.configure(width=100)

        self.Message3_1 = tk.Message(self.Frame1)
        self.Message3_1.place(relx=0.121, rely=0.329, relheight=0.121
                , relwidth=0.11)
        self.Message3_1.configure(background="#f2f6fe")
        self.Message3_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1.configure(foreground="#000000")
        self.Message3_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1.configure(highlightcolor="#000000")
        self.Message3_1.configure(padx="1")
        self.Message3_1.configure(pady="1")
        self.Message3_1.configure(text='''Maths''')
        self.Message3_1.configure(width=100)

        self.Message3_1_1_1_1_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_1.place(relx=0.254, rely=0.329, relheight=0.121
                , relwidth=0.11)
        self.Message3_1_1_1_1_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_1.configure(padx="1")
        self.Message3_1_1_1_1_1_1.configure(pady="1")
        self.Message3_1_1_1_1_1_1.configure(text='''English''')
        self.Message3_1_1_1_1_1_1.configure(width=100)

        self.Message3_1_1_1_1_1_2_1_2 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1_2.place(relx=0.508, rely=0.329
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1_2.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1_2.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1_2.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1_2.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1_2.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1_2.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1_2.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1_2.configure(text='''Games''')
        self.Message3_1_1_1_1_1_2_1_2.configure(width=100)

        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1.place(relx=0.629, rely=0.329
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1.configure(text='''Chemistry''')
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1_1.configure(width=100)

        self.Message3_2_2_1 = tk.Message(self.Frame1)
        self.Message3_2_2_1.place(relx=0.883, rely=0.329, relheight=0.121
                , relwidth=0.11)
        self.Message3_2_2_1.configure(background="#f2f6fe")
        self.Message3_2_2_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_2_2_1.configure(foreground="#000000")
        self.Message3_2_2_1.configure(highlightbackground="#d9d9d9")
        self.Message3_2_2_1.configure(highlightcolor="#000000")
        self.Message3_2_2_1.configure(padx="1")
        self.Message3_2_2_1.configure(pady="1")
        self.Message3_2_2_1.configure(text='''Physics''')
        self.Message3_2_2_1.configure(width=100)

        self.Message3_1_1_1_1_1_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_1_1.place(relx=0.254, rely=0.494, relheight=0.121
                , relwidth=0.11)
        self.Message3_1_1_1_1_1_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_1_1.configure(padx="1")
        self.Message3_1_1_1_1_1_1_1.configure(pady="1")
        self.Message3_1_1_1_1_1_1_1.configure(text='''Maths''')
        self.Message3_1_1_1_1_1_1_1.configure(width=100)

        self.Message3_1_1_1_1_1_2_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1_1.place(relx=0.375, rely=0.514
                , relheight=0.101, relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1_1.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1_1.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1_1.configure(text='''Chemistry''')
        self.Message3_1_1_1_1_1_2_1_1.configure(width=100)

        self.Message3_1_1_1_1_1_2_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1.place(relx=0.375, rely=0.329, relheight=0.121
                , relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1.configure(justify='center')
        self.Message3_1_1_1_1_1_2_1.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1.configure(text='''Physics
Lab''')
        self.Message3_1_1_1_1_1_2_1.configure(width=100)

        self.Message3_1_1_1_1_1_2_1_1_2 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1_1_2.place(relx=0.508, rely=0.494
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1_1_2.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1_1_2.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1_1_2.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1_1_2.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1_1_2.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1_1_2.configure(justify='center')
        self.Message3_1_1_1_1_1_2_1_1_2.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1_1_2.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1_1_2.configure(text='''IP
Lab''')
        self.Message3_1_1_1_1_1_2_1_1_2.configure(width=100)

        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1.place(relx=0.64, rely=0.514
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1.configure(text='''English''')
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1_1.configure(width=100)

        self.Message3_2_1_1 = tk.Message(self.Frame1)
        self.Message3_2_1_1.place(relx=0.762, rely=0.494, relheight=0.121
                , relwidth=0.11)
        self.Message3_2_1_1.configure(background="#f2f6fe")
        self.Message3_2_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_2_1_1.configure(foreground="#000000")
        self.Message3_2_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_2_1_1.configure(highlightcolor="#000000")
        self.Message3_2_1_1.configure(padx="1")
        self.Message3_2_1_1.configure(pady="1")
        self.Message3_2_1_1.configure(text='''Phe/
Painting''')
        self.Message3_2_1_1.configure(width=100)

        self.Message3_2_2_1_1 = tk.Message(self.Frame1)
        self.Message3_2_2_1_1.place(relx=0.883, rely=0.494, relheight=0.121
                , relwidth=0.11)
        self.Message3_2_2_1_1.configure(background="#f2f6fe")
        self.Message3_2_2_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_2_2_1_1.configure(foreground="#000000")
        self.Message3_2_2_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_2_2_1_1.configure(highlightcolor="#000000")
        self.Message3_2_2_1_1.configure(padx="1")
        self.Message3_2_2_1_1.configure(pady="1")
        self.Message3_2_2_1_1.configure(text='''IP''')
        self.Message3_2_2_1_1.configure(width=100)

        self.Message3_1_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1.place(relx=0.121, rely=0.679, relheight=0.121
                , relwidth=0.11)
        self.Message3_1_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1.configure(foreground="#000000")
        self.Message3_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1.configure(padx="1")
        self.Message3_1_1_1.configure(pady="1")
        self.Message3_1_1_1.configure(text='''Chemistry''')
        self.Message3_1_1_1.configure(width=100)

        self.Message3_1_1_1_1_1_1_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_1_1_1.place(relx=0.254, rely=0.679
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_1_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_1_1_1.configure(padx="1")
        self.Message3_1_1_1_1_1_1_1_1.configure(pady="1")
        self.Message3_1_1_1_1_1_1_1_1.configure(text='''English''')
        self.Message3_1_1_1_1_1_1_1_1.configure(width=100)

        self.Message3_1_1_1_1_1_2_1_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1_1_1.place(relx=0.375, rely=0.679
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1_1_1.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1_1_1.configure(text='''Maths''')
        self.Message3_1_1_1_1_1_2_1_1_1.configure(width=100)

        self.Message3_1_1_1_1_1_2_1_1_1_2 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1_1_1_2.place(relx=0.508, rely=0.679
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1_1_1_2.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1_1_1_2.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1_1_1_2.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_2.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1_1_1_2.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_2.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1_1_1_2.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1_1_1_2.configure(text='''IP''')
        self.Message3_1_1_1_1_1_2_1_1_1_2.configure(width=100)

        self.Message3_2_1_1_1 = tk.Message(self.Frame1)
        self.Message3_2_1_1_1.place(relx=0.762, rely=0.679, relheight=0.121
                , relwidth=0.11)
        self.Message3_2_1_1_1.configure(background="#f2f6fe")
        self.Message3_2_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_2_1_1_1.configure(foreground="#000000")
        self.Message3_2_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_2_1_1_1.configure(highlightcolor="#000000")
        self.Message3_2_1_1_1.configure(padx="1")
        self.Message3_2_1_1_1.configure(pady="1")
        self.Message3_2_1_1_1.configure(text='''Library''')
        self.Message3_2_1_1_1.configure(width=100)

        self.Message3_2_1_1_1_2 = tk.Message(self.Frame1)
        self.Message3_2_1_1_1_2.place(relx=0.883, rely=0.679, relheight=0.121
                , relwidth=0.11)
        self.Message3_2_1_1_1_2.configure(background="#f2f6fe")
        self.Message3_2_1_1_1_2.configure(font="-family {Segoe UI} -size 16")
        self.Message3_2_1_1_1_2.configure(foreground="#000000")
        self.Message3_2_1_1_1_2.configure(highlightbackground="#d9d9d9")
        self.Message3_2_1_1_1_2.configure(highlightcolor="#000000")
        self.Message3_2_1_1_1_2.configure(padx="1")
        self.Message3_2_1_1_1_2.configure(pady="1")
        self.Message3_2_1_1_1_2.configure(text='''Games''')
        self.Message3_2_1_1_1_2.configure(width=100)

        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1.place(relx=0.629, rely=0.679
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1.configure(text='''Physics''')
        self.Message3_1_1_1_1_1_2_1_1_1_3_1_1.configure(width=100)

        self.Message3_1_1_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1.place(relx=0.121, rely=0.844, relheight=0.121
                , relwidth=0.11)
        self.Message3_1_1_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1.configure(padx="1")
        self.Message3_1_1_1_1.configure(pady="1")
        self.Message3_1_1_1_1.configure(text='''English''')
        self.Message3_1_1_1_1.configure(width=100)

        self.Message3_1_1_1_1_1_1_1_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_1_1_1_1.place(relx=0.254, rely=0.844
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_1_1_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_1_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_1_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_1_1_1_1.configure(padx="1")
        self.Message3_1_1_1_1_1_1_1_1_1.configure(pady="1")
        self.Message3_1_1_1_1_1_1_1_1_1.configure(text='''Maths''')
        self.Message3_1_1_1_1_1_1_1_1_1.configure(width=100)

        self.Message3_1_1_1_1_1_2_1_1_1_3_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1_1_1_3_1.place(relx=0.629, rely=0.844
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1_1_1_3_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1_1_1_3_1.configure(text='''Physics''')
        self.Message3_1_1_1_1_1_2_1_1_1_3_1.configure(width=100)

        self.Message3_2_1_1_1_1_1 = tk.Message(self.Frame1)
        self.Message3_2_1_1_1_1_1.place(relx=0.883, rely=0.844, relheight=0.121
                , relwidth=0.11)
        self.Message3_2_1_1_1_1_1.configure(background="#f2f6fe")
        self.Message3_2_1_1_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_2_1_1_1_1_1.configure(foreground="#000000")
        self.Message3_2_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_2_1_1_1_1_1.configure(highlightcolor="#000000")
        self.Message3_2_1_1_1_1_1.configure(padx="1")
        self.Message3_2_1_1_1_1_1.configure(pady="1")
        self.Message3_2_1_1_1_1_1.configure(text='''IP''')
        self.Message3_2_1_1_1_1_1.configure(width=100)

        self.Message3_1_1_1_1_1_2_1_1_1_3 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1_1_1_3.place(relx=0.508, rely=0.844
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1_1_1_3.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1_1_1_3.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1_1_1_3.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_3.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1_1_1_3.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_3.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1_1_1_3.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1_1_1_3.configure(text='''Phe/
Painting''')
        self.Message3_1_1_1_1_1_2_1_1_1_3.configure(width=100)

        self.Message3_2_1_1_1_1 = tk.Message(self.Frame1)
        self.Message3_2_1_1_1_1.place(relx=0.762, rely=0.844, relheight=0.121
                , relwidth=0.11)
        self.Message3_2_1_1_1_1.configure(background="#f2f6fe")
        self.Message3_2_1_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_2_1_1_1_1.configure(foreground="#000000")
        self.Message3_2_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_2_1_1_1_1.configure(highlightcolor="#000000")
        self.Message3_2_1_1_1_1.configure(padx="1")
        self.Message3_2_1_1_1_1.configure(pady="1")
        self.Message3_2_1_1_1_1.configure(text='''Chemistry''')
        self.Message3_2_1_1_1_1.configure(width=100)

        self.Message3_1_1_1_1_1_2_1_1_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2_1_1_1_1.place(relx=0.375, rely=0.844
                , relheight=0.121, relwidth=0.11)
        self.Message3_1_1_1_1_1_2_1_1_1_1.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2_1_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2_1_1_1_1.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2_1_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2_1_1_1_1.configure(justify='center')
        self.Message3_1_1_1_1_1_2_1_1_1_1.configure(padx="1")
        self.Message3_1_1_1_1_1_2_1_1_1_1.configure(pady="1")
        self.Message3_1_1_1_1_1_2_1_1_1_1.configure(text='''Chemistry
Lab''')
        self.Message3_1_1_1_1_1_2_1_1_1_1.configure(width=100)

        self.Message3_2_1 = tk.Message(self.Frame1)
        self.Message3_2_1.place(relx=0.762, rely=0.329, relheight=0.121
                , relwidth=0.11)
        self.Message3_2_1.configure(background="#f2f6fe")
        self.Message3_2_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_2_1.configure(foreground="#000000")
        self.Message3_2_1.configure(highlightbackground="#d9d9d9")
        self.Message3_2_1.configure(highlightcolor="#000000")
        self.Message3_2_1.configure(justify='center')
        self.Message3_2_1.configure(padx="1")
        self.Message3_2_1.configure(pady="1")
        self.Message3_2_1.configure(text='''IP
Lab''')
        self.Message3_2_1.configure(width=100)

        self.Message3_1_1_1_1_1_2 = tk.Message(self.Frame1)
        self.Message3_1_1_1_1_1_2.place(relx=0.375, rely=0.165, relheight=0.121
                , relwidth=0.11)
        self.Message3_1_1_1_1_1_2.configure(background="#f2f6fe")
        self.Message3_1_1_1_1_1_2.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1_1_1_1_2.configure(foreground="#000000")
        self.Message3_1_1_1_1_1_2.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1_1_2.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1_1_2.configure(padx="1")
        self.Message3_1_1_1_1_1_2.configure(pady="1")
        self.Message3_1_1_1_1_1_2.configure(text='''Physics''')
        self.Message3_1_1_1_1_1_2.configure(width=100)

        self.Message3_1_1 = tk.Message(self.Frame1)
        self.Message3_1_1.place(relx=0.121, rely=0.494, relheight=0.121
                , relwidth=0.11)
        self.Message3_1_1.configure(background="#f2f6fe")
        self.Message3_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Message3_1_1.configure(foreground="#000000")
        self.Message3_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1.configure(padx="1")
        self.Message3_1_1.configure(pady="1")
        self.Message3_1_1.configure(text='''Physics''')
        self.Message3_1_1.configure(width=100)

        self.Message2_1_1 = tk.Message(self.top)
        self.Message2_1_1.place(relx=0.143, rely=0.548, relheight=0.073
                , relwidth=0.06)
        self.Message2_1_1.configure(background="#f2f6fe")
        self.Message2_1_1.configure(font="-family {Segoe UI} -size 12")
        self.Message2_1_1.configure(foreground="#000000")
        self.Message2_1_1.configure(highlightbackground="#d9d9d9")
        self.Message2_1_1.configure(highlightcolor="#000000")
        self.Message2_1_1.configure(padx="1")
        self.Message2_1_1.configure(pady="1")
        self.Message2_1_1.configure(text='''DAY-3''')
        self.Message2_1_1.configure(width=80)

        self.Message2_1_1_1 = tk.Message(self.top)
        self.Message2_1_1_1.place(relx=0.143, rely=0.667, relheight=0.073
                , relwidth=0.06)
        self.Message2_1_1_1.configure(background="#f2f6fe")
        self.Message2_1_1_1.configure(font="-family {Segoe UI} -size 12")
        self.Message2_1_1_1.configure(foreground="#000000")
        self.Message2_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message2_1_1_1.configure(highlightcolor="#000000")
        self.Message2_1_1_1.configure(padx="1")
        self.Message2_1_1_1.configure(pady="1")
        self.Message2_1_1_1.configure(text='''DAY-4''')
        self.Message2_1_1_1.configure(width=80)

        self.Message2_1_1_1_1 = tk.Message(self.top)
        self.Message2_1_1_1_1.place(relx=0.143, rely=0.8, relheight=0.073
                , relwidth=0.06)
        self.Message2_1_1_1_1.configure(background="#f2f6fe")
        self.Message2_1_1_1_1.configure(font="-family {Segoe UI} -size 12")
        self.Message2_1_1_1_1.configure(foreground="#000000")
        self.Message2_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message2_1_1_1_1.configure(highlightcolor="#000000")
        self.Message2_1_1_1_1.configure(padx="1")
        self.Message2_1_1_1_1.configure(pady="1")
        self.Message2_1_1_1_1.configure(text='''DAY-5''')
        self.Message2_1_1_1_1.configure(width=80)

        self.Message2_2_1 = tk.Message(self.top)
        self.Message2_2_1.place(relx=0.317, rely=0.193, relheight=0.073
                , relwidth=0.06)
        self.Message2_2_1.configure(background="#f2f6fe")
        self.Message2_2_1.configure(font="-family {Segoe UI} -size 12")
        self.Message2_2_1.configure(foreground="#000000")
        self.Message2_2_1.configure(highlightbackground="#d9d9d9")
        self.Message2_2_1.configure(highlightcolor="#000000")
        self.Message2_2_1.configure(padx="1")
        self.Message2_2_1.configure(pady="1")
        self.Message2_2_1.configure(text='''Period-2''')
        self.Message2_2_1.configure(width=80)

        self.Message2_2_1_1 = tk.Message(self.top)
        self.Message2_2_1_1.place(relx=0.4, rely=0.193, relheight=0.073
                , relwidth=0.06)
        self.Message2_2_1_1.configure(background="#f2f6fe")
        self.Message2_2_1_1.configure(font="-family {Segoe UI} -size 12")
        self.Message2_2_1_1.configure(foreground="#000000")
        self.Message2_2_1_1.configure(highlightbackground="#d9d9d9")
        self.Message2_2_1_1.configure(highlightcolor="#000000")
        self.Message2_2_1_1.configure(padx="1")
        self.Message2_2_1_1.configure(pady="1")
        self.Message2_2_1_1.configure(text='''Period-3''')
        self.Message2_2_1_1.configure(width=80)

        self.Message2_2_1_1_1 = tk.Message(self.top)
        self.Message2_2_1_1_1.place(relx=0.483, rely=0.193, relheight=0.073
                , relwidth=0.06)
        self.Message2_2_1_1_1.configure(background="#f2f6fe")
        self.Message2_2_1_1_1.configure(font="-family {Segoe UI} -size 12")
        self.Message2_2_1_1_1.configure(foreground="#000000")
        self.Message2_2_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message2_2_1_1_1.configure(highlightcolor="#000000")
        self.Message2_2_1_1_1.configure(padx="1")
        self.Message2_2_1_1_1.configure(pady="1")
        self.Message2_2_1_1_1.configure(text='''Period-4''')
        self.Message2_2_1_1_1.configure(width=80)

        self.Message2_2_1_1_1_1 = tk.Message(self.top)
        self.Message2_2_1_1_1_1.place(relx=0.573, rely=0.193, relheight=0.073
                , relwidth=0.06)
        self.Message2_2_1_1_1_1.configure(background="#f2f6fe")
        self.Message2_2_1_1_1_1.configure(font="-family {Segoe UI} -size 12")
        self.Message2_2_1_1_1_1.configure(foreground="#000000")
        self.Message2_2_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message2_2_1_1_1_1.configure(highlightcolor="#000000")
        self.Message2_2_1_1_1_1.configure(padx="1")
        self.Message2_2_1_1_1_1.configure(pady="1")
        self.Message2_2_1_1_1_1.configure(text='''Period-5''')
        self.Message2_2_1_1_1_1.configure(width=80)

        self.Message2_1 = tk.Message(self.top)
        self.Message2_1.place(relx=0.143, rely=0.43, relheight=0.073
                , relwidth=0.06)
        self.Message2_1.configure(background="#f2f6fe")
        self.Message2_1.configure(font="-family {Segoe UI} -size 12")
        self.Message2_1.configure(foreground="#000000")
        self.Message2_1.configure(highlightbackground="#d9d9d9")
        self.Message2_1.configure(highlightcolor="#000000")
        self.Message2_1.configure(padx="1")
        self.Message2_1.configure(pady="1")
        self.Message2_1.configure(text='''DAY-2''')
        self.Message2_1.configure(width=80)

        self.Message2_2 = tk.Message(self.top)
        self.Message2_2.place(relx=0.656, rely=0.193, relheight=0.073
                , relwidth=0.06)
        self.Message2_2.configure(background="#f2f6fe")
        self.Message2_2.configure(font="-family {Segoe UI} -size 12")
        self.Message2_2.configure(foreground="#000000")
        self.Message2_2.configure(highlightbackground="#d9d9d9")
        self.Message2_2.configure(highlightcolor="#000000")
        self.Message2_2.configure(padx="1")
        self.Message2_2.configure(pady="1")
        self.Message2_2.configure(text='''Period-6''')
        self.Message2_2.configure(width=80)

        self.Message2_2_2 = tk.Message(self.top)
        self.Message2_2_2.place(relx=0.739, rely=0.193, relheight=0.073
                , relwidth=0.06)
        self.Message2_2_2.configure(background="#f2f6fe")
        self.Message2_2_2.configure(font="-family {Segoe UI} -size 12")
        self.Message2_2_2.configure(foreground="#000000")
        self.Message2_2_2.configure(highlightbackground="#d9d9d9")
        self.Message2_2_2.configure(highlightcolor="#000000")
        self.Message2_2_2.configure(padx="1")
        self.Message2_2_2.configure(pady="1")
        self.Message2_2_2.configure(text='''Period-7''')
        self.Message2_2_2.configure(width=80)

        self.Message1 = tk.Message(self.top)
        self.Message1.place(relx=0.121, rely=0.044, relheight=0.117
                , relwidth=0.205)
        self.Message1.configure(background="#dbe6ff")
        self.Message1.configure(font="-family {Arial Black} -size 30 -weight bold")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="#000000")
        self.Message1.configure(justify='center')
        self.Message1.configure(padx="1")
        self.Message1.configure(pady="1")
        self.Message1.configure(text='''Time Table''')
        self.Message1.configure(width=272)

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.845, rely=0.919, height=35, width=90)
        self.Button1.configure(activebackground="#f2f6fe")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#f2f6fe")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 9")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Back''')

def start_up():
    time_table_support.main()

if __name__ == '__main__':
    time_table_support.main()




