#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Oct 08, 2024 02:52:20 PM IST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import wlc_st_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1536x793+-8+-8")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#dbe6ff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.Message1 = tk.Message(self.top)
        self.Message1.place(relx=0.055, rely=0.091, relheight=0.137
                , relwidth=0.299)
        self.Message1.configure(background="#dbe6ff")
        self.Message1.configure(font="-family {Sitka Display} -size 72 -weight bold")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="#000000")
        self.Message1.configure(padx="1")
        self.Message1.configure(pady="1")
        self.Message1.configure(text='''WELCOME''')
        self.Message1.configure(width=462)

        self.Button1_1_2 = tk.Button(self.top)
        self.Button1_1_2.place(relx=-0.174, rely=0.232, height=120, width=120)
        self.Button1_1_2.configure(activebackground="#d9d9d9")
        self.Button1_1_2.configure(activeforeground="black")
        self.Button1_1_2.configure(background="#d9d9d9")
        self.Button1_1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_1_2.configure(font="-family {Segoe UI} -size 9")
        self.Button1_1_2.configure(foreground="#000000")
        self.Button1_1_2.configure(highlightbackground="#d9d9d9")
        self.Button1_1_2.configure(highlightcolor="#000000")
        self.Button1_1_2.configure(text='''Button''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.prof = tk.Button(self.top)
        self.prof.place(relx=0.109, rely=0.46, height=120, width=120)
        self.prof.configure(activebackground="#d9d9d9")
        self.prof.configure(activeforeground="black")
        self.prof.configure(background="#dbe6ff")
        self.prof.configure(disabledforeground="#a3a3a3")
        self.prof.configure(foreground="#000000")
        self.prof.configure(highlightbackground="#d9d9d9")
        self.prof.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"../Users/kr866/Desktop/ip/School-management-/Test/Image/Details1.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.prof.configure(image=_img0)
        self.prof.configure(relief="flat")

        self.msg_stu = tk.Button(self.top)
        self.msg_stu.place(relx=0.328, rely=0.46, height=120, width=120)
        self.msg_stu.configure(activebackground="#d9d9d9")
        self.msg_stu.configure(activeforeground="black")
        self.msg_stu.configure(background="#dbe6ff")
        self.msg_stu.configure(disabledforeground="#a3a3a3")
        self.msg_stu.configure(font="-family {Segoe UI} -size 9")
        self.msg_stu.configure(foreground="#000000")
        self.msg_stu.configure(highlightbackground="#d9d9d9")
        self.msg_stu.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"../Users/kr866/Desktop/ip/School-management-/Test/Image/Message1.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.msg_stu.configure(image=_img1)
        self.msg_stu.configure(relief="flat")

        self.asg_stu = tk.Button(self.top)
        self.asg_stu.place(relx=0.547, rely=0.46, height=120, width=120)
        self.asg_stu.configure(activebackground="#d9d9d9")
        self.asg_stu.configure(activeforeground="black")
        self.asg_stu.configure(background="#dbe6ff")
        self.asg_stu.configure(disabledforeground="#a3a3a3")
        self.asg_stu.configure(font="-family {Segoe UI} -size 9")
        self.asg_stu.configure(foreground="#000000")
        self.asg_stu.configure(highlightbackground="#d9d9d9")
        self.asg_stu.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"../Users/kr866/Desktop/ip/School-management-/Test/Image/Assignment1.png")
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.asg_stu.configure(image=_img2)
        self.asg_stu.configure(relief="flat")
        self.asg_stu.configure(text='''Button''')

        self.atd_stu = tk.Button(self.top)
        self.atd_stu.place(relx=0.766, rely=0.46, height=120, width=120)
        self.atd_stu.configure(activebackground="#d9d9d9")
        self.atd_stu.configure(activeforeground="black")
        self.atd_stu.configure(background="#dbe6ff")
        self.atd_stu.configure(disabledforeground="#a3a3a3")
        self.atd_stu.configure(font="-family {Segoe UI} -size 9")
        self.atd_stu.configure(foreground="#000000")
        self.atd_stu.configure(highlightbackground="#d9d9d9")
        self.atd_stu.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"../Users/kr866/Desktop/ip/School-management-/Test/Image/Attendance1.png")
        global _img3
        _img3 = tk.PhotoImage(file=photo_location)
        self.atd_stu.configure(image=_img3)
        self.atd_stu.configure(relief="flat")
        self.atd_stu.configure(text='''Button''')

        self.tbd = tk.Button(self.top)
        self.tbd.place(relx=0.109, rely=0.719, height=120, width=120)
        self.tbd.configure(activebackground="#d9d9d9")
        self.tbd.configure(activeforeground="black")
        self.tbd.configure(background="#dbe6ff")
        self.tbd.configure(disabledforeground="#a3a3a3")
        self.tbd.configure(font="-family {Segoe UI} -size 9")
        self.tbd.configure(foreground="#000000")
        self.tbd.configure(highlightbackground="#d9d9d9")
        self.tbd.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"../Users/kr866/Desktop/ip/School-management-/Test/Image/Time_table1.png")
        global _img4
        _img4 = tk.PhotoImage(file=photo_location)
        self.tbd.configure(image=_img4)
        self.tbd.configure(relief="flat")
        self.tbd.configure(text='''Button''')

        self.Message3 = tk.Message(self.top)
        self.Message3.place(relx=0.124, rely=0.631, relheight=0.024
                , relwidth=0.046)
        self.Message3.configure(background="#dbe6ff")
        self.Message3.configure(font="-family {Segoe UI} -size 14")
        self.Message3.configure(foreground="black")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="#000000")
        self.Message3.configure(padx="1")
        self.Message3.configure(pady="1")
        self.Message3.configure(text='''Details''')
        self.Message3.configure(width=70)

        self.Message3_1 = tk.Message(self.top)
        self.Message3_1.place(relx=0.339, rely=0.618, relheight=0.039
                , relwidth=0.059)
        self.Message3_1.configure(background="#dbe6ff")
        self.Message3_1.configure(font="-family {Segoe UI} -size 14")
        self.Message3_1.configure(foreground="black")
        self.Message3_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1.configure(highlightcolor="#000000")
        self.Message3_1.configure(padx="1")
        self.Message3_1.configure(pady="1")
        self.Message3_1.configure(text='''Message''')
        self.Message3_1.configure(width=90)

        self.Message3_1_1 = tk.Message(self.top)
        self.Message3_1_1.place(relx=0.553, rely=0.618, relheight=0.039
                , relwidth=0.066)
        self.Message3_1_1.configure(background="#dbe6ff")
        self.Message3_1_1.configure(font="-family {Segoe UI} -size 14")
        self.Message3_1_1.configure(foreground="black")
        self.Message3_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1.configure(padx="1")
        self.Message3_1_1.configure(pady="1")
        self.Message3_1_1.configure(text='''Assignment''')
        self.Message3_1_1.configure(width=101)

        self.Message3_1_1_1 = tk.Message(self.top)
        self.Message3_1_1_1.place(relx=0.775, rely=0.618, relheight=0.039
                , relwidth=0.074)
        self.Message3_1_1_1.configure(background="#dbe6ff")
        self.Message3_1_1_1.configure(font="-family {Segoe UI} -size 14")
        self.Message3_1_1_1.configure(foreground="black")
        self.Message3_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1.configure(padx="1")
        self.Message3_1_1_1.configure(pady="1")
        self.Message3_1_1_1.configure(text='''Attendance''')
        self.Message3_1_1_1.configure(width=112)

        self.Message3_1_1_1_1 = tk.Message(self.top)
        self.Message3_1_1_1_1.place(relx=0.111, rely=0.883, relheight=0.039
                , relwidth=0.074)
        self.Message3_1_1_1_1.configure(background="#dbe6ff")
        self.Message3_1_1_1_1.configure(font="-family {Segoe UI} -size 14")
        self.Message3_1_1_1_1.configure(foreground="black")
        self.Message3_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Message3_1_1_1_1.configure(highlightcolor="#000000")
        self.Message3_1_1_1_1.configure(padx="1")
        self.Message3_1_1_1_1.configure(pady="1")
        self.Message3_1_1_1_1.configure(text='''Time Table''')
        self.Message3_1_1_1_1.configure(width=112)

        self.back = tk.Button(self.top)
        self.back.place(relx=0.859, rely=0.868, height=40, width=90)
        self.back.configure(activebackground="#d9d9d9")
        self.back.configure(activeforeground="black")
        self.back.configure(background="#f2f6fe")
        self.back.configure(disabledforeground="#a3a3a3")
        self.back.configure(foreground="black")
        self.back.configure(highlightbackground="#d9d9d9")
        self.back.configure(highlightcolor="#000000")
        self.back.configure(text='''Back''')

        self.Message2 = tk.Message(self.top)
        self.Message2.place(relx=0.065, rely=0.227, relheight=0.091
                , relwidth=0.152)
        self.Message2.configure(background="#dbe6ff")
        self.Message2.configure(font="-family {Sitka Display} -size 48 -weight bold")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="#000000")
        self.Message2.configure(padx="1")
        self.Message2.configure(pady="1")
        self.Message2.configure(text='''Student''')
        self.Message2.configure(width=283)

def start_up():
    wlc_st_support.main()

if __name__ == '__main__':
    wlc_st_support.main()




