#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Oct 09, 2024 12:17:00 PM PDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #dbe6ff -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1280x649+340+90
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 701
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    entry "$top.ent62" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 164 
    vTcl:DefineAlias "$top.ent62" "enter_total" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent63" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 134 
    vTcl:DefineAlias "$top.ent63" "Enter_present" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but67" \
        -activebackground #d9d9d9 -activeforeground black -background #f2f6fe \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Black} -size 11 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "BACK" 
    vTcl:DefineAlias "$top.but67" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab60" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 18 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Absent:" 
    vTcl:DefineAlias "$top.lab60" "Absent" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab58" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 18 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Total:" 
    vTcl:DefineAlias "$top.lab58" "total" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 15 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Sec:" 
    vTcl:DefineAlias "$top.lab52" "sec" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 24 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Enter Student Id:" 
    vTcl:DefineAlias "$top.lab48" "student_id" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab59" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 18 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Present:" 
    vTcl:DefineAlias "$top.lab59" "present" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but66" \
        -activebackground #d9d9d9 -activeforeground black -background #f2f6fe \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Black} -size 11 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "SUBMIT" 
    vTcl:DefineAlias "$top.but66" "submit" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent49" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 254 
    vTcl:DefineAlias "$top.ent49" "Enter_student_id" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 15 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Roll no :" 
    vTcl:DefineAlias "$top.lab53" "roll_no" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 14 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Name:" 
    vTcl:DefineAlias "$top.lab50" "name" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 15 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Class:" 
    vTcl:DefineAlias "$top.lab51" "class" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab61" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 18 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Percent:" 
    vTcl:DefineAlias "$top.lab61" "percent" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent64" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 164 
    vTcl:DefineAlias "$top.ent64" "Enter_absent" vTcl:WidgetProc "Toplevel1" 1
    text "$top.tex73" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 34 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 174 \
        -wrap word 
    $top.tex73 configure -font "TkTextFont"
    $top.tex73 insert end text
    vTcl:DefineAlias "$top.tex73" "enter_percent" vTcl:WidgetProc "Toplevel1" 1
    text "$top.tex69" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 24 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 204 \
        -wrap word 
    $top.tex69 configure -font "TkTextFont"
    $top.tex69 insert end text
    vTcl:DefineAlias "$top.tex69" "enter_name" vTcl:WidgetProc "Toplevel1" 1
    text "$top.tex70" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 24 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 194 \
        -wrap word 
    $top.tex70 configure -font "TkTextFont"
    $top.tex70 insert end text
    vTcl:DefineAlias "$top.tex70" "enter_class" vTcl:WidgetProc "Toplevel1" 1
    text "$top.tex71" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 26 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 205 \
        -wrap word 
    $top.tex71 configure -font "TkTextFont"
    $top.tex71 insert end text
    vTcl:DefineAlias "$top.tex71" "enter_sec" vTcl:WidgetProc "Toplevel1" 1
    text "$top.tex72" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -height 4 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 10 \
        -wrap word 
    $top.tex72 configure -font "TkTextFont"
    $top.tex72 insert end text
    vTcl:DefineAlias "$top.tex72" "enter_roll" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but68" \
        -activebackground #d9d9d9 -activeforeground black -background #f2f6fe \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Search" 
    vTcl:DefineAlias "$top.but68" "search" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab47" \
        -activebackground #dbe6ff -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Sitka Display} -size 48 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Attendance" 
    vTcl:DefineAlias "$top.lab47" "heading" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent62 \
        -in $top -x 0 -relx 0.609 -y 0 -rely 0.331 -width 164 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent63 \
        -in $top -x 0 -relx 0.609 -y 0 -rely 0.424 -width 164 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but67 \
        -in $top -x 0 -relx 0.711 -y 0 -rely 0.878 -width 137 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.523 -y 0 -rely 0.508 -width 0 -relwidth 0.082 \
        -height 0 -relheight 0.062 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.523 -y 0 -rely 0.324 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.063 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.724 -width 0 -relwidth 0.041 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.324 -width 0 -relwidth 0.213 \
        -height 0 -relheight 0.063 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.523 -y 0 -rely 0.416 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.but66 \
        -in $top -x 0 -relx 0.633 -y 0 -rely 0.616 -width 117 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.416 -width 274 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.786 -width 0 -relwidth 0.066 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.601 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.663 -width 0 -relwidth 0.058 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 0 -relx 0.531 -y 0 -rely 0.74 -width 0 -relwidth 0.081 \
        -height 0 -relheight 0.063 -anchor nw -bordermode ignore 
    place $top.ent64 \
        -in $top -x 0 -relx 0.609 -y 0 -rely 0.516 -width 164 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tex73 \
        -in $top -x 0 -relx 0.613 -y 0 -rely 0.74 -width 0 -relwidth 0.136 \
        -height 0 -relheight 0.052 -anchor nw -bordermode ignore 
    place $top.tex69 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.601 -width 0 -relwidth 0.159 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.tex70 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.663 -width 0 -relwidth 0.152 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.tex71 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.724 -width 0 -relwidth 0.152 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.tex72 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.794 -width 0 -relwidth 0.152 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.but68 \
        -in $top -x 0 -relx 0.285 -y 0 -rely 0.408 -width 57 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.055 -y 0 -rely 0.062 -width 0 -relwidth 0.316 \
        -height 0 -relheight 0.109 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

