#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Oct 07, 2024 03:21:44 AM PDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    login_(1)_png "../Users/LENOVO/Downloads/login (1).png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m49 -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1280x649+340+90
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 701
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m49" \
        -activebackground #98e1f1 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    label "$top.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Text} -size 22 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -image login_(1)_png 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    canvas "$top.can51" \
        -background #dbe6ff -borderwidth 2 -closeenough 1.0 -height 713 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 491 
    vTcl:DefineAlias "$top.can51" "background" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.can51
    label "$site_3_0.lab52" \
        -activebackground #dbe6ff -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Symbol} -size 22 -weight bold -underline 1" \
        -foreground black -highlightbackground #98e1f1 \
        -highlightcolor #000000 -text "  LOGIN  " 
    vTcl:DefineAlias "$site_3_0.lab52" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 11 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "USER ID" 
    vTcl:DefineAlias "$site_3_0.lab53" "user_id" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Black} -size 11 -weight bold" \
        -foreground black -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "PASSWORD:" 
    vTcl:DefineAlias "$site_3_0.lab56" "Label3" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_3_0.ent57" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 194 
    vTcl:DefineAlias "$site_3_0.ent57" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_3_0.ent54" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 204 
    vTcl:DefineAlias "$site_3_0.ent54" "Enter" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but58" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "SUBMIT" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "submit" 
    vTcl:DefineAlias "$site_3_0.but58" "Button1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.285 -y 0 -rely 0.056 -width 0 \
        -relwidth 0.638 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.142 -y 0 -rely 0.252 -width 0 \
        -relwidth 0.232 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.142 -y 0 -rely 0.393 -width 0 \
        -relwidth 0.252 -height 0 -relheight 0.045 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent57 \
        -in $site_3_0 -x 0 -relx 0.142 -y 0 -rely 0.435 -width 194 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 0 -relx 0.142 -y 0 -rely 0.295 -width 204 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but58 \
        -in $site_3_0 -x 0 -relx 0.264 -y 0 -rely 0.617 -width 137 \
        -relwidth 0 -height 46 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab48 \
        -in $top -x 0 -relx -0.023 -y 0 -width 0 -relwidth 0.627 -height 0 \
        -relheight 1.023 -anchor nw -bordermode ignore 
    place $top.can51 \
        -in $top -x 0 -relx 0.594 -y 0 -rely -0.031 -width 0 -relwidth 0.384 \
        -height 0 -relheight 1.099 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

