#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Oct 09, 2024 03:51:48 AM PDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m52 -background #dbe6ff -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1280x649+340+90
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 701
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m52" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    label "$top.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 14" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Adm. no :" 
    vTcl:DefineAlias "$top.lab53" "adm" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 14" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Mother's Name:" 
    vTcl:DefineAlias "$top.lab55" "mom" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 14" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Address:" 
    vTcl:DefineAlias "$top.lab56" "address" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 14" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Phone:" 
    vTcl:DefineAlias "$top.lab57" "phone" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 14" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Class:" 
    vTcl:DefineAlias "$top.lab50" "class" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 14" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Roll no:" 
    vTcl:DefineAlias "$top.lab51" "roll" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 14" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Father's Name:" 
    vTcl:DefineAlias "$top.lab54" "dad" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Variable Display} -size 14" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Name:" 
    vTcl:DefineAlias "$top.lab49" "name" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but66" \
        -activebackground #d9d9d9 -activeforeground black -background #f2f6fe \
        -command "SUBMIT" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Black} -size 13 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "SUBMIT" 
    vTcl:DefineAlias "$top.but66" "submit" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but67" \
        -activebackground #d9d9d9 -activeforeground black -background #f2f6fe \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI Black} -size 13 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "BACK" 
    vTcl:DefineAlias "$top.but67" "back" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent58" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 384 
    vTcl:DefineAlias "$top.ent58" "Enter_dad" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent62" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 244 
    vTcl:DefineAlias "$top.ent62" "Enter_adm" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent61" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 254 
    vTcl:DefineAlias "$top.ent61" "Enter_roll" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent60" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 254 
    vTcl:DefineAlias "$top.ent60" "Enter_class" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent59" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 254 
    vTcl:DefineAlias "$top.ent59" "Enter_name" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent63" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 264 
    vTcl:DefineAlias "$top.ent63" "Enter_mom" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent64" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 314 
    vTcl:DefineAlias "$top.ent64" "enter_add" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent65" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 314 
    vTcl:DefineAlias "$top.ent65" "Enter_phone" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #dbe6ff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Sitka Display} -size 48 -underline 1" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Student Enrollment " 
    vTcl:DefineAlias "$top.lab48" "heading" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab53 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.462 -width 0 -relwidth 0.08 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.586 -width 0 -relwidth 0.12 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.647 -width 0 -relwidth 0.113 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.709 -width 0 -relwidth 0.097 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.339 -width 0 -relwidth 0.055 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.401 -width 0 -relwidth 0.066 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.524 -width 0 -relwidth 0.102 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.277 -width 0 -relwidth 0.066 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.but66 \
        -in $top -x 0 -relx 0.242 -y 0 -rely 0.817 -width 177 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but67 \
        -in $top -x 0 -relx 0.703 -y 0 -rely 0.817 -width 177 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent58 \
        -in $top -x 0 -relx 0.195 -y 0 -rely 0.524 -width 384 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent62 \
        -in $top -x 0 -relx 0.195 -y 0 -rely 0.462 -width 384 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent61 \
        -in $top -x 0 -relx 0.195 -y 0 -rely 0.401 -width 384 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent60 \
        -in $top -x 0 -relx 0.195 -y 0 -rely 0.339 -width 384 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent59 \
        -in $top -x 0 -relx 0.195 -y 0 -rely 0.293 -width 384 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent63 \
        -in $top -x 0 -relx 0.195 -y 0 -rely 0.586 -width 384 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent64 \
        -in $top -x 0 -relx 0.195 -y 0 -rely 0.647 -width 384 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent65 \
        -in $top -x 0 -relx 0.195 -y 0 -rely 0.709 -width 384 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.062 -width 0 -relwidth 0.409 \
        -height 0 -relheight 0.109 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

