#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Oct 08, 2024 02:52:02 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    details1_png "../Users/kr866/Desktop/ip/School-management-/Test/Image/Details1.png" 
    message1_png "../Users/kr866/Desktop/ip/School-management-/Test/Image/Message1.png" 
    assignment1_png "../Users/kr866/Desktop/ip/School-management-/Test/Image/Assignment1.png" 
    attendance1_png "../Users/kr866/Desktop/ip/School-management-/Test/Image/Attendance1.png" 
    time_table1_png "../Users/kr866/Desktop/ip/School-management-/Test/Image/Time_table1.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m55 -background #dbe6ff -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1536x793+468+138
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    message "$top.mes48" \
        -background #dbe6ff \
        -font "-family {Sitka Display} -size 72 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -padx 1 -pady 1 -text "WELCOME" -width 462 
    vTcl:DefineAlias "$top.mes48" "Message1" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but54" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Button" 
    vTcl:DefineAlias "$top.but54" "Button1_1_2" vTcl:WidgetProc "Toplevel1" 1
    menu "$top.m55" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    button "$top.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #dbe6ff \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -image details1_png -relief flat 
    vTcl:DefineAlias "$top.but50" "prof" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #dbe6ff \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -image message1_png -relief flat 
    vTcl:DefineAlias "$top.but51" "msg_stu" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but52" \
        -activebackground #d9d9d9 -activeforeground black -background #dbe6ff \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -image assignment1_png -relief flat \
        -text "Button" 
    vTcl:DefineAlias "$top.but52" "asg_stu" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but53" \
        -activebackground #d9d9d9 -activeforeground black -background #dbe6ff \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -image attendance1_png -relief flat \
        -text "Button" 
    vTcl:DefineAlias "$top.but53" "atd_stu" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but56" \
        -activebackground #d9d9d9 -activeforeground black -background #dbe6ff \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -image time_table1_png -relief flat \
        -text "Button" 
    vTcl:DefineAlias "$top.but56" "tbd" vTcl:WidgetProc "Toplevel1" 1
    message "$top.mes57" \
        -background #dbe6ff -font "-family {Segoe UI} -size 14" \
        -foreground black -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -padx 1 -pady 1 -text "Details" -width 70 
    vTcl:DefineAlias "$top.mes57" "Message3" vTcl:WidgetProc "Toplevel1" 1
    message "$top.mes58" \
        -background #dbe6ff -font "-family {Segoe UI} -size 14" \
        -foreground black -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -padx 1 -pady 1 -text "Message" -width 90 
    vTcl:DefineAlias "$top.mes58" "Message3_1" vTcl:WidgetProc "Toplevel1" 1
    message "$top.mes59" \
        -background #dbe6ff -font "-family {Segoe UI} -size 14" \
        -foreground black -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -padx 1 -pady 1 -text "Assignment" -width 101 
    vTcl:DefineAlias "$top.mes59" "Message3_1_1" vTcl:WidgetProc "Toplevel1" 1
    message "$top.mes60" \
        -background #dbe6ff -font "-family {Segoe UI} -size 14" \
        -foreground black -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -padx 1 -pady 1 -text "Attendance" -width 112 
    vTcl:DefineAlias "$top.mes60" "Message3_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    message "$top.mes61" \
        -background #dbe6ff -font "-family {Segoe UI} -size 14" \
        -foreground black -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -padx 1 -pady 1 -text "Time Table" -width 112 
    vTcl:DefineAlias "$top.mes61" "Message3_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but62" \
        -activebackground #d9d9d9 -activeforeground black -background #f2f6fe \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground black -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Back" 
    vTcl:DefineAlias "$top.but62" "back" vTcl:WidgetProc "Toplevel1" 1
    message "$top.mes49" \
        -background #dbe6ff \
        -font "-family {Sitka Display} -size 48 -weight bold" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -padx 1 -pady 1 -text "Student" -width 283 
    vTcl:DefineAlias "$top.mes49" "Message2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.mes48 \
        -in $top -x 0 -relx 0.055 -y 0 -rely 0.091 -width 0 -relwidth 0.299 \
        -height 0 -relheight 0.137 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx -0.174 -y 0 -rely 0.232 -width 120 -relwidth 0 \
        -height 120 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.109 -y 0 -rely 0.46 -width 120 -relwidth 0 \
        -height 120 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.328 -y 0 -rely 0.46 -width 120 -relwidth 0 \
        -height 120 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 0 -relx 0.547 -y 0 -rely 0.46 -width 120 -relwidth 0 \
        -height 120 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.766 -y 0 -rely 0.46 -width 120 -relwidth 0 \
        -height 120 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 0 -relx 0.109 -y 0 -rely 0.719 -width 120 -relwidth 0 \
        -height 120 -relheight 0 -anchor nw -bordermode ignore 
    place $top.mes57 \
        -in $top -x 0 -relx 0.124 -y 0 -rely 0.631 -width 0 -relwidth 0.046 \
        -height 0 -relheight 0.024 -anchor nw -bordermode ignore 
    place $top.mes58 \
        -in $top -x 0 -relx 0.339 -y 0 -rely 0.618 -width 0 -relwidth 0.059 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.mes59 \
        -in $top -x 0 -relx 0.553 -y 0 -rely 0.618 -width 0 -relwidth 0.066 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.mes60 \
        -in $top -x 0 -relx 0.775 -y 0 -rely 0.618 -width 0 -relwidth 0.073 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.mes61 \
        -in $top -x 0 -relx 0.111 -y 0 -rely 0.883 -width 0 -relwidth 0.074 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 0 -relx 0.859 -y 0 -rely 0.868 -width 90 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.mes49 \
        -in $top -x 0 -relx 0.065 -y 0 -rely 0.227 -width 0 -relwidth 0.152 \
        -height 0 -relheight 0.091 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

